os: linux
dist: bionic
language: python
python:
- '3.6'
- '3.7'
- 3.8-dev
- nightly
matrix:
  include:
  - os: osx
    language: shell
    osx_image: xcode11
before_install:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install python3-pip libdbus-glib-1-dev; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo pip3 install --upgrade pip; fi
install:
- pip3 install --upgrade pip
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then pip3 install dbus-python; fi
- pip3 install .[dev]
script:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then pytest --cov-config=.coveragerc --cov=SwSpotify
  tests/test_spotify.py::LinuxTests; pytest --cov-config=.coveragerc --cov=SwSpotify
    tests/test_spotify.py::WebTests; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then pytest --cov-config=.coveragerc --cov=SwSpotify
  tests/test_spotify.py::DarwinTests;  pytest --cov-config=.coveragerc --cov=SwSpotify
    tests/test_spotify.py::WebTests; fi
after_success:
- bash <(curl -s https://codecov.io/bash) -Z
deploy:
  provider: pypi
  user: aadibajpai
  password:
    secure: HKsFXeDU0xt8gwNiUva1A6VN+4b1R1I1Y+ZJRZdQmEGAwd1PQbAKWyedsFyDifhnedLs821rlnxNybDAcji9Vl4IyVGvr8Rucw82iI9F0SEWvRCG4TmgAVUCZOO1+8vluqKFs2dLcLupekRt0O5qX6fPge/+YsTLaCqYGhLtMTHMtnAfp2t7ngBy866yZWmDk3KqhvDdSvvVGyegm1XFbPBMPIywjtD8FvNRQBpGq8+8tdOwoSRYv0AYrzzN9rZk7lk143CejLJgo+848aGEx+Ue8FZYqtKoQ0w3+DirN4mdMZvnoEOAhX+Ku59870EZLsUfIQ+EeLhUiMyz9rS7DyMw12EhjXnMbKWC7ZsTy8ASfw3V/l91sRsHMTzXtJrXK9sutd+5MgYTXSQFhdwZ+exJ5x2P93SL/ojk+iV2akywiggQejGkL8CfzaF7ZdskM5L6VxLt2zvn61TB3hYyyKp5cU6byFr9Zy/uRoMpK6w95VmHoLlrBjnNEIZmaKb0iOTBYdSb3IPBKLNXUc/epwsj5m/yajAq/PqN9smhZntIoZCqxYIXlXGwGr+ynttmDZnveRfGdK8OK9cILsXcgMRDLy2qoPrNJelddTDbUmcj1nAGIvhN7xHA7c3Qbz79nfxeJRwqKzLQHgFfWLCVjvg5wWnysgdhjMLSaHlFHYs=
  skip_existing: true
  distributions: sdist bdist_wheel
  on:
    tags: true
